from django.contrib import admin
from django.urls import include, path

from guest import views

urlpatterns = [
   path('students',views.students,name="students"),
   path('students/<id>',views.students,name="students"),
   path('login',views.logins,name="login"),
   path('district',views.state,name="district"),
   path('location',views.district,name="location"),
   path('location/<id>',views.district,name="location"),
   path('course',views.courses,name="course"),
   path('getsubject',views.getsubjectall,name="subject"),
   path('subject',views.subject,name="subject"),
   path('subject/<id>',views.subject,name="subject"),
   path('staff',views.staffs,name="staff"),
   path('activate/<id>',views.activate,name="activate"),
   path('deactivate/<id>',views.deactivate,name="deactivate"),
   path('staff/<id>',views.staffedit,name="staff"),
   path('staffupdate/<id>',views.staffedit,name="staffupdate"),
   path('message',views.messages,name="message"),
   path('message/<id>',views.messages,name="message"),
   path('logout',views.logout,name="logout"),
   path('staffgetbystudent/<id>',views.staffgetbystudent,name="staffgetbystudent"),
   path('getsubjectwithstaff',views.getsubjectwithstaff,name="getsubjectwithstaff"),
   path('getsubjectwithstaff/<id>',views.getsubjectwithstaff,name="getsubjectwithstaff"),
   path('activatesubject/<id>',views.activatesubject,name="activatesubject"),
   path('deactivatesubject/<id>',views.deactivatesubject,name="deactivatesubject"),
   path('getstaff/<id>',views.getstaff,name="getstaff"),
   path('getstudentforstaff/<id>',views.getstudentforstaff,name="getstudentforstaff"),
   path('present/<id>',views.present,name="present"),
   path('absent/<id>',views.absent,name="absent"),
   path('attendancehistory',views.attendancehistory,name="attendancehistory"),
   path('attendance/<id>',views.attendances,name="attendance"),
   path('attendancehistory/<id>',views.attendancehistorywithid,name="attendancehistorywithid"),
   path('attendancedate',views.attendancedate,name="attendancedate"),
   path('getstudent/<id>',views.getstudent,name="getstudent"),
   path('updateprofile/<id>',views.updateprofile,name="updateprofile"),
   path('changepassword/<id>',views.changepassword,name="changepassword"),
   path('checkform/<id>',views.checkform,name="checkform"),
   path('sendmessage/<id>',views.sendmessage,name="sendmessage"),
   path('staffmessages/<id>/<studentid>',views.staffmessages,name="staffmessages"),
   path('getstudentsinchat/<id>',views.getstudentsinchat,name="getstudentsinchat"),
   path('sendstaffmessage/<id>/<studentid>',views.sendstaffmessage,name="sendstaffmessage"),
   path('addevent',views.addevent,name="addevent"),
   path('addevent/<id>',views.addevent,name="addevent"),
   path('geteventsbyid/<id>',views.geteventsbyid,name="geteventsbyid"),
   path('updateevent/<id>',views.updateevent,name="updateevent"),
   path('eventsubmitform',views.eventsubmitform,name="eventsubmitform"),
   path('getstudentsdetailes/<id>',views.getstudentsdetailes,name="getstudentsdetailes"),
   path('otp',views.otpfunction,name="otp"),
   path('otp/<id>',views.otpfunction,name="otp"),
   path('otpdone/<id>',views.otpdone,name="otpdone"),
   path('changepasswordbyotp/<id>',views.changepasswordbyotp,name="changepasswordbyotp"),
   path('getcount/<id>',views.getcount,name="getcount"),
   path('status/<id>/<studentid>',views.status,name="changestatus"),
   path('studentlogout/<id>',views.studentlogout,name="studentlogout"),
   path('getstudentswithactive',views.getstudentswithactive,name="getstudentswithactive"),
   path('getsubjectwithid/<id>',views.subjectwithid,name="subjectwithid"),
   path('updatesubject/<id>',views.updatesubject,name="updatesubject"),
   path('getbankdetails',views.getbankdetails,name="getbankdetails"),
   path('getsubjectwithsubjectid/<id>',views.getsubjectwithsubjectid,name="getsubjectwithsubjectid"),
   path('cardsubmit/<id>',views.cardsubmit,name="cardsubmit"),
   path('banksubmit/<id>',views.banksubmit,name="banksubmit"),
   path('feesreport/<id>',views.feesreport,name="feesreport"),
   path('getfeesbystudentid/<id>',views.getfeesbystudentid,name="getfeesbystudentid"),
   path('feespaid/<id>',views.feespaid,name="feespaid")
   
]
   
   

